Added the submodules .privates

diff --git a/bashrc/bashrc.d/ssh b/bashrc/bashrc.d/ssh
--- a/bashrc/bashrc.d/ssh
+++ b/bashrc/bashrc.d/ssh
@@ -10,14 +10,20 @@ function start_agent {
   chmod 600 "${SSH_ENV}"
   . "${SSH_ENV}" > /dev/null
   /usr/bin/ssh-add;
+  EXIT_CODE=$?
+  if [ $EXIT_CODE -ne 0 ]; then
+      echo "Failed to add SSH identity (exit code ${EXIT_CODE})"
+  fi
 }
 
 # Source SSH settings, if applicable
-if [ -f "${SSH_ENV}" ]; then
-  . "${SSH_ENV}" > /dev/null
-  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
+if [ -d "$HOME/.ssh" ]; then
+  if [ -f "${SSH_ENV}" ]; then
+    . "${SSH_ENV}" > /dev/null
+    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
+      start_agent;
+    }
+  else
     start_agent;
-  }
-else
-  start_agent;
+  fi
 fi
